# Generated by Django 5.2.8 on 2025-11-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("poster_original", models.ImageField(upload_to="movies/posters/")),
                ("backdrop_original", models.ImageField(upload_to="movies/backdrops/")),
                ("description", models.TextField()),
                ("year", models.IntegerField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("category", models.CharField(max_length=100)),
                ("is_new", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
