# Generated by Django 5.2.8 on 2025-11-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A URL-friendly version of the name, e.g., 'sci-fi'",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="movie",
            name="category",
        ),
        migrations.AddField(
            model_name="movie",
            name="is_from_festival",
            field=models.BooleanField(
                default=False, help_text="is this movie from a festival?"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_student_production",
            field=models.BooleanField(
                default=False, help_text="Is this a 'Made by Students' film?"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this movie visible to users?"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_new",
            field=models.BooleanField(default=False, help_text="is this movie new?"),
        ),
        migrations.AddField(
            model_name="movie",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="streaming.category"
            ),
        ),
    ]
